on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: src
          recurse: true
          output_dir: docs
          config_file: jsdoc.conf.json
