on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build docs
        uses: andstor/jsdoc-action@v1
        with:
          recurse: true
          config_file: jsdoc.conf.json
          - name: Push changes to main branch
            run: |
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add .
              git commit -m "Automated commit from GitHub Action"
              git push origin main

